### ISSUE TITLE
Параметр temperature

### ISSUE THREAD

**Issue by MrBooroondook** [OldCodersClub/LariskaBot#10]
Какой у Лариски стоит параметр temperature? Что-то не нашел....

**Comment by MrBooroondook** [comment]
Имеется в виду, когда реквест в OpenAI делает?

**Comment by Aleksey-Voko** [comment]
Этот параметр для другой языковой модели. У неё сейчас модель gpt-3.5-turbo. Там вообще нет подобных параметров.

**Comment by Aleksey-Voko** [comment]
Вкратце, модель gpt-3.5-turbo оптимизирована для чатов и болтунов. И её ещё потом индусами вручную дообучали, чтоб косячные ответы не выдавала.
